services:
  - title: "Journal of Imaging"
    role: Guest Editor
    journal: y

  - title: "Electronics"
    role: Guest Editor
    journal: y
    
  - title: "npj Digital Medicine"
    role: Reviewer
    journal: y

  - title: "IEEE Transactions on Neural Networks and Learning Systems"
    role: Reviewer
    journal: y

  - title: "IEEE Transactions on Cybernetics"
    role: Reviewer
    journal: y

  - title: "Expert Systems With Applications"
    role: Reviewer
    journal: y
    
  - title: "Machine Learning"
    role: Reviewer
    journal: y

  - title: "Transactions on Machine Learning Research"
    role: Reviewer
    journal: y

  - title: "IEEE Journal of Biomedical and Health Informatics"
    role: Reviewer
    journal: y
    
  - title: "Data Mining and Knowledge Discovery"
    role: Reviewer
    journal: y

  - title: "The Pacific-Asia Conference on Knowledge Discovery and Data Mining （PAKDD 2025）"
    role: Session Chair
    conference: y

  - title: "The Thirty-ninth Annual Conference on Neural Information Processing Systems（NeurIPS 2025）"
    role: PC Member
    conference: y
    
  - title: "The Thirteenth International Conference on Learning Representations （ICLR 2025）"
    role: PC Member
    conference: y
    
  - title: "International Joint Conference on Artificial Intelligence (IJCAI 2025)"
    role: PC Member
    conference: y

  - title: " The 32nd ACM SIGKDD Conference on Knowledge Discovery and Data Mining (KDD 2026)"
    role: PC Member
    conference: y

  - title: "The 17th Asian Conference on Machine Learning (ACML 2025)"
    role: PC Member
    conference: y

  - title: "European Conference on Machine Learning and Principles and Practice of Knowledge Discovery in Databases (ECMLPKDD 2025)"
    role: PC Member
    conference: y


  - title: "The 11th IEEE International Conference on Data Science and Advanced Analytics (DSAA 2024)"
    role: PC Member
    conference: y
